### ISSUE TITLE
Fails in React Native: UInt8Array.from() missing

### ISSUE THREAD

**Issue by alfreddatakillen** [LinusU/encode-utf8#1]
`.from` is undefined on the UInt8Array object in React Native 0.54 (running iOS), so the module just triggers an exception. I guess the same thing would also happen on browsers that have not implemented `.from()` yet.

**Comment by alfreddatakillen** [comment]
I created a pull request which fixes this: https://github.com/LinusU/encode-utf8/pull/2

**Comment by LinusU** [comment]
Which version of iOS are you running? I think that is should work in iOS 11+ 🤔

**Comment by alfreddatakillen** [comment]
I believe it is all about which version of V8 that React Native uses when bundling. "Funny" thing is that it works on Android with React Native 0.54, but not iOS, since React Native uses a different version of V8 on iOS.

But yeah, whatever, thanks for merging the pull request and publishing 1.0.2 so fast! Have a nice day!

**Comment by LinusU** [comment]
> It is all about which version of V8 that React Native uses when bundling.

I don't think so since AFAIK Apple doesn't allow executing writable memory in user-space apps, thus V8 wouldn't be able to JIT and would be dirt slow 🤔 

I'm quite sure it uses Apple's JavaScript Core on iOS...

**Comment by alfreddatakillen** [comment]
Oh, yeah, rings a bell. You are probably right. We have tested on iOS 11.2, and it says `.from` is undefined. But, yeah, fixed now! Thanks a lot again!
